service: crawler
app: crawler
org: fpvrodeo

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:DeleteMessage"
        - "sqs:DeleteMessageBatch"
        - "sqs:SendMessageBatch"
        - "sqs:ReceiveMessage"
        - "sqs:SendMessage"
      Resource:
        Fn::GetAtt:
          - "HobbyRcQueue"
          - "Arn"

functions:
  hobbycrawl:
    handler: crawler.hobbyRcCrawl
    memorySize: 256
    timeout: 900
    environment:
      HOBBYRC_QUEUE:
        Ref: HobbyRcQueue

resources:
  Resources:
    HobbyRcQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "HobbyRC"
        RedrivePolicy:
          maxReceiveCount: "5"
          deadLetterTargetArn:
            Fn::GetAtt:
              - "HobbyRcDLQ"
              - "Arn"
    HobbyRcDLQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "HobbyRC-DLQ"
  Outputs:
    HobbyRCQueueUrl:
      Description: "HobbyRC Queue URL"
      Value:
        Ref: "HobbyRcQueue"
